eureka:
  instance:
  prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
name:
  value: alibou
spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0
