server:
  port: 8070
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql:5432/order
    username: alibou
    password: alibou
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      bootstrap-servers: kafka:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.alibou.ecommerce.kafka.OrderConfirmation

application:
  config:
    customer-url: http://customer-service:8090/api/v1/customers
    payment-url: http://payment-service:8060/api/v1/payments
    product-url: http://product-service:8050/api/v1/products
